// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_12_Cinema.Data;

#nullable disable

namespace Task_12_Cinema.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231026153253_add-sessions-to-film")]
    partial class addsessionstofilm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task_12_Cinema.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ShortBio")
                        .HasMaxLength(1500)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "MiddleName", "LastName")
                        .IsUnique()
                        .HasFilter("[MiddleName] IS NOT NULL AND [LastName] IS NOT NULL");

                    b.ToTable("Director", null, t =>
                        {
                            t.HasCheckConstraint("CK_Director_FirstName", "LEN(TRIM([FirstName])) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Martin",
                            LastName = "Scorsese",
                            ShortBio = "We`re talking about the guy who made Taxi Driver here! No one has more classics than Scorsese, including directors like James Cameron and David Fincher. His resume includes Raging Bull, Goodfellas, Mean Streets, Cape Fear, Shutter Island, and The Last Waltz. Famously, it took Scorsese a while to win an Oscar, but they eventually gave him one for The Departed."
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Guillermo",
                            LastName = "del Toro",
                            ShortBio = "For the longest time, Guillermo del Toro was one of those under-the-radar directors. Then he made Pan`s Labyrinth, Hellboy, and The Shape of Water. Now you can`t watch a football game without seeing an ad for Nightmare Alley. His success is further proof that good work+hard work will eventually= acclaim."
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Christopher",
                            LastName = "Nolan",
                            ShortBio = "Like Fincher, Nolan is a track-record director. He`s 11 for 11 on feature films. Sure, he`s only made a couple of great films (Dunkirk, The Dark Knight), but he`s never made a movie that isn`t worth watching."
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "James",
                            LastName = "Cameron",
                            ShortBio = "Is anyone talking about Apichatapong? Not really. Cameron, on the other hand? He`s a living legend. He`s discussed more than any other director on here. Whether we`re talking about Terminator 2 or The Titanic, Cameron has managed to stay relevant for as long as I`ve been alive. His Avatar films will keep it that way for years to come."
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Steven",
                            LastName = "Spielberg",
                            ShortBio = "Pick an age, any age: Spielberg has the power to make you feel like a kid again. It doesn`t matter if you`re 8 or 88, ET,  Indiana Jones, and Jurassic Park will have you grinning from ear-to-ear. Even at 75, the man is still finding ways to make us smile. "
                        });
                });

            modelBuilder.Entity("Task_12_Cinema.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("GenreId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Film", null, t =>
                        {
                            t.HasCheckConstraint("CK_Film_Name", "LEN(TRIM([Name])) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Its plot centers on a series of Oklahoma murders in the Osage Nation during the 1920s, committed after oil was discovered on tribal land.",
                            DirectorId = 1,
                            GenreId = 4,
                            Name = "Killers of the Flower Moon"
                        },
                        new
                        {
                            Id = 2,
                            Description = "In 1954, U.S. Marshal Edward \"Teddy\" Daniels and his new partner Chuck Aule travel to Ashecliffe Hospital for the criminally insane on Shutter Island, Boston Harbor to investigate the disappearance of Rachel Solando, a patient of the hospital who had previously drowned her three children.",
                            DirectorId = 1,
                            GenreId = 6,
                            Name = "Shutter Island"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The film draws inspiration from the debut comic Hellboy: Seed of Destruction. In the film, a charismatic demon-turned-investigator named \"Hellboy\" works with the secretive Bureau of Paranormal Research and Defense to suppress paranormal threats, but a resurrected sorcerer seeks to make Hellboy fulfill his destiny by triggering the apocalypse.",
                            DirectorId = 2,
                            GenreId = 2,
                            Name = "Hellboy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "In 2067, humanity is facing extinction following a global famine caused by ecocide. As a result, ex-NASA pilot, Joseph Cooper, is forced to work as a farmer, with his son Tom, daughter Murph and father-in-law Donald.",
                            DirectorId = 3,
                            GenreId = 5,
                            Name = "Interstellar"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Two men arrive separately in 1984 Los Angeles, having time traveled from 2029. One is a cybernetic assassin known as a Terminator, programmed to hunt and kill a woman named Sarah Connor. The other is a human soldier named Kyle Reese, intent on stopping it. They both steal guns and clothing.",
                            DirectorId = 4,
                            GenreId = 1,
                            Name = "The Terminator"
                        },
                        new
                        {
                            Id = 6,
                            Description = "In 1969, FBI agent Carl Hanratty arrives in Marseille, France, to pick up a prisoner named Frank Abagnale Jr. who became ill due to the prison`s conditions.",
                            DirectorId = 5,
                            GenreId = 2,
                            Name = "Catch Me If You Can"
                        });
                });

            modelBuilder.Entity("Task_12_Cinema.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genre", null, t =>
                        {
                            t.HasCheckConstraint("CK_Genre_Name", "LEN(TRIM([Name])) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Associated with particular types of spectacle (e.g., explosions, chases, combat).",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Implies a narrative that is defined by a journey (often including some form of pursuit) and is usually located within a fantasy or exoticized setting.",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Defined by events that are primarily intended to make the audience laugh.",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Focused on emotions and defined by conflict, often looking to reality rather than sensationalism.",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Films defined by situations that transcend natural laws and/or by settings inside a fictional universe, with narratives that are often inspired by or involve human myths.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Films that seek to elicit fear or disgust in the audience for entertainment purposes.",
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("Task_12_Cinema.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValue(new DateTime(2023, 10, 26, 15, 32, 53, 491, DateTimeKind.Utc).AddTicks(6315));

                    b.Property<int>("FilmId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("FilmId", "EventDateTime")
                        .IsUnique();

                    b.ToTable("Session", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDateTime = new DateTime(2023, 11, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 1
                        },
                        new
                        {
                            Id = 2,
                            EventDateTime = new DateTime(2023, 11, 2, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 1
                        },
                        new
                        {
                            Id = 3,
                            EventDateTime = new DateTime(2023, 11, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 2
                        },
                        new
                        {
                            Id = 4,
                            EventDateTime = new DateTime(2023, 11, 2, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 2
                        },
                        new
                        {
                            Id = 5,
                            EventDateTime = new DateTime(2023, 11, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 3
                        },
                        new
                        {
                            Id = 6,
                            EventDateTime = new DateTime(2023, 11, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 3
                        },
                        new
                        {
                            Id = 7,
                            EventDateTime = new DateTime(2023, 11, 3, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 4
                        },
                        new
                        {
                            Id = 8,
                            EventDateTime = new DateTime(2023, 11, 2, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 4
                        },
                        new
                        {
                            Id = 9,
                            EventDateTime = new DateTime(2023, 11, 2, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 5
                        },
                        new
                        {
                            Id = 10,
                            EventDateTime = new DateTime(2023, 11, 3, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 5
                        },
                        new
                        {
                            Id = 11,
                            EventDateTime = new DateTime(2023, 11, 3, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 6
                        },
                        new
                        {
                            Id = 12,
                            EventDateTime = new DateTime(2023, 11, 4, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 6
                        });
                });

            modelBuilder.Entity("Task_12_Cinema.Models.Film", b =>
                {
                    b.HasOne("Task_12_Cinema.Models.Director", "Director")
                        .WithMany("Films")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Task_12_Cinema.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Task_12_Cinema.Models.Session", b =>
                {
                    b.HasOne("Task_12_Cinema.Models.Film", "Film")
                        .WithMany("Sessions")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Task_12_Cinema.Models.Director", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("Task_12_Cinema.Models.Film", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
